# Server
server:
  port: 8080

# Database config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf8
    username: seomoon
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  #Tymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    mode: HTML
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    thymeleaf:
      extras:
        springsecurity5:
          order: 0
logging:
  level:
    org:
      hibernate: info
      thymeleaf: off